apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: istio-app-production

namespace: istio-app

resources:
  - ../../base

patches:
  - path: replica-patch.yaml
    target:
      kind: Deployment
      name: istio-test-app
  - path: resource-patch.yaml
    target:
      kind: Deployment
      name: istio-test-app

labels:
  - pairs:
      environment: production
      version: v1.0.0
