apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-gitops-demo

resources:
  - ../../base

replicas:
  - name: istio-test-app
    count: 2

images:
  - name: nginx
    newTag: "1.21"
