apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-test-app
  namespace: istio-gitops-demo
  labels:
    app: istio-test-app
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: istio-test-app
      version: v1
  template:
    metadata:
      labels:
        app: istio-test-app
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: istio-test-app
      containers:
      - name: app
        image: nginx:1.21
        ports:
        - containerPort: 80
          name: http
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: false
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: nginx-html-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-test-app
  namespace: istio-gitops-demo
  labels:
    app: istio-test-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-config
  namespace: istio-gitops-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>GitOps Automation Demo</title>
        <style>
            body { 
                font-family: Arial, sans-serif; 
                margin: 40px;
                background: linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%);
                color: white;
                text-align: center;
            }
            .container {
                background: rgba(255,255,255,0.1);
                padding: 30px;
                border-radius: 10px;
                backdrop-filter: blur(10px);
            }
            h1 { color: #ffeb3b; font-size: 2.5em; }
            .status { 
                padding: 15px; 
                border-radius: 8px; 
                margin: 15px 0; 
                background: rgba(255,255,255,0.2);
                border: 2px solid #ffeb3b;
            }
            .highlight {
                background: rgba(255,255,255,0.3);
                padding: 20px;
                border-radius: 10px;
                font-size: 1.3em;
                font-weight: bold;
                margin: 20px 0;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 🚀 LIVE GitOps Automation Test - WOW WOW MANMOHAN!</h1>
            <div class="highlight">
                🎉 Great job ----WOW WOW MANMOHAN RULES! 🎉
            </div>
            
            <div class="status">
                <h2>📊 GitOps Status</h2>
                <p><strong>Repository:</strong> ✅ GitHub Connected</p>
                <p><strong>ArgoCD:</strong> ✅ Auto-Sync Enabled</p>
                <p><strong>Deployment:</strong> ✅ Automated</p>
                <p><strong>Istio:</strong> ✅ Service Mesh Active</p>
            </div>
            
            <div class="status">
                <h2>🔒 Security Features</h2>
                <p>• ✅ Istio mTLS (STRICT mode)</p>
                <p>• ✅ Authorization policies</p>
                <p>• ✅ Istio Gateway access</p>
                <p>• ✅ PostgreSQL integration ready</p>
            </div>
            
            <div class="status">
                <h2>🔄 Automation Flow</h2>
                <p><strong>GitHub Push → ArgoCD Sync → EKS Deploy → Live!</strong></p>
                <p>Complete end-to-end automation working!</p>
            </div>
            
            <div class="highlight">
                🌟 🎊 LIVE UPDATE: Great job ----WOW WOW MANMOHAN RULES! 🎊 🌟<br>
                <strong>Great job ----WOW WOW MANMOHAN RULES!</strong>
            </div>
        </div>
    </body>
    </html>
