apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gitops-gateway
  namespace: istio-gitops-demo
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "gitops.istio.local"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: istio-gitops-vs
  namespace: istio-gitops-demo
spec:
  hosts:
  - "gitops.istio.local"
  gateways:
  - istio-gitops-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: istio-test-app-service
        port:
          number: 80
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
