apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: istio-app-base

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - security.yaml

commonLabels:
  app: istio-test-app
  managed-by: argocd
  
images:
  - name: nginx
    newTag: "1.21"
